  CREATE TABLE STUDENT(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    AGE INTEGER,
    NAME VARCHAR(255),
    SEX INTEGER,
    ADDRESS_ID BIGINT,
    PRIMARY KEY (ID)
  );
  	CREATE TABLE ADDRESS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ADDRESS VARCHAR(255),
    ZIP_CODE VARCHAR(255),
    PRIMARY KEY (ID)
  );
  
  	CREATE TABLE GRADE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
  );
	CREATE TABLE TEACHER(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    GRADE_ID BIGINT,
    PRIMARY KEY (ID)
  );
  	CREATE TABLE STUDENT_TEACHER(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    STUDENT_ID BIGINT NOT NULL,
    TEACHER_ID BIGINT NOT NULL,
    PRIMARY KEY (ID)
  );