spring:
  profiles:
    active: dev
  jackson:
    defaultPropertyInclusion: NON_NULL

server:    
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
      
endpoints:
  cors:
    allowCredentials: true
    allowedMethods:
      - GET
      - POST
    allowedHeaders: '*'
    allowedOrigins: '*'
    

    
