spring:
  profiles:
    active: dev
    
server:    
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
      
endpoints:
  cors:
    allowCredentials: true
    allowedMethods:
      - GET
      - POST
    allowedHeaders: '*'
    allowedOrigins: '*'
    
example.message:
  resprefix: 您发送的消息是：
  
mybatis:
  mapperLocations: classpath*:/mappers/*Mapper.xml
  configLocation: classpath:mybatis-config.xml
