server:
  port: 28080
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8  

endpoints:
  cors:
    allowCredentials: true
    allowedMethods:
      - GET
      - POST
    allowedHeaders: '*'
    allowedOrigins: '*'

mybatis:
  mapperLocations: classpath*:/example/dao/*Mapper.xml  
  
example:
  validating:
    token: k2data
    cipher: sha1
    encoding: utf-8
  message:
    resprefix: 您发送的消息是：