server:
  port: 18080
  
logging:
  config: classpath:log4j2-dev.xml
  
spring:
  data:
    elasticsearch:
      clusterName: els-study
      clusterNodes: 10.1.10.20:9300
      node.local: false
      repositories.enabled: true
      