spring:
  profiles:
    active: dev
 
endpoints:
  cors:
    allowCredentials: true
    allowedMethods:
      - GET
      - POST
    allowedHeaders: '*'
    allowedOrigins: '*'  
  shutdown:
    enabled: true

mybatis:
  mapperLocations: classpath*:/example/dao/*Mapper.xml  

management:
  contextPath: /actuator

example:
  validating:
     token: k2data
     cipher: sha1
     encoding: utf-8
  message:
     resprefix: 您发送的消息是：