server:
  port: 18080
  
logging:
  config: classpath:log4j2-dev.xml
  
spring:
  data:
    elasticsearch:
      clusterName: els-study
      clusterNodes: 10.1.10.20:9300
      node.local: false
      repositories.enabled: true

  datasource:
    url: jdbc:h2:mem:employee_db
    username: sa
    password: sa
#    schema: classpath:schema.sql
#    data: classpath:data.sql
    
  h2.console:
    path: /h2/console
    enabled: true
      