server:
  port: 18080
  
logging:
  config: classpath:log4j2-dev.xml

spring:
  datasource:
    url: jdbc:h2:mem:message:db
    schema: classpath:schema.sql
    data: classpath:data.sql
    
management:
  security:
    enabled: false
  contextPath: /actuator   

endpoints.shutdown.enabled: true